repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^frontend/
    -   id: end-of-file-fixer
        exclude: ^frontend/
    -   id: check-yaml
        exclude: ^frontend/
    -   id: check-json
        exclude: ^frontend/
    -   id: check-added-large-files
        exclude: ^frontend/
    -   id: check-ast
        exclude: ^frontend/
    -   id: check-merge-conflict
        exclude: ^frontend/
    -   id: detect-private-key
        exclude: ^frontend/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^frontend/

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        exclude: ^frontend/

#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.5.1
#    hooks:
#    -   id: mypy
#        additional_dependencies: [types-requests, types-PyYAML]
#        exclude: ^frontend/
